import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

export async function createTempDir(prefix = "splat-editor-test-") {
  return fs.mkdtemp(path.join(os.tmpdir(), prefix));
}

export function createSyntheticPlyBuffer({
  rows = [],
  extraRestCount = 0,
}) {
  const properties = [
    "x",
    "y",
    "z",
    "nx",
    "ny",
    "nz",
    "f_dc_0",
    "f_dc_1",
    "f_dc_2",
    ...Array.from({ length: extraRestCount }, (_, index) => `f_rest_${index}`),
    "opacity",
    "scale_0",
    "scale_1",
    "scale_2",
    "rot_0",
    "rot_1",
    "rot_2",
    "rot_3",
  ];

  const rowStride = properties.length * 4;
  const header = [
    "ply",
    "format binary_little_endian 1.0",
    "comment Generated by synthetic test fixture",
    "comment Vertical Axis: z",
    `element vertex ${rows.length}`,
    ...properties.map((property) => `property float ${property}`),
    "end_header",
    "",
  ].join("\n");

  const body = Buffer.alloc(rows.length * rowStride);
  const view = new DataView(body.buffer, body.byteOffset, body.byteLength);

  rows.forEach((row, rowIndex) => {
    properties.forEach((property, propertyIndex) => {
      const byteOffset = rowIndex * rowStride + propertyIndex * 4;
      const value = row[property] ?? 0;
      view.setFloat32(byteOffset, value, true);
    });
  });

  return Buffer.concat([Buffer.from(header, "utf8"), body]);
}

export async function writeSyntheticPly(filePath, options) {
  const buffer = createSyntheticPlyBuffer(options);
  await fs.writeFile(filePath, buffer);
  return buffer;
}

export async function createSyntheticTarGz({ tarPath, plyPath, metadata }) {
  const workDir = await createTempDir("splat-editor-tar-");
  const localPlyPath = path.join(workDir, "splat.ply");
  const localMetadataPath = path.join(workDir, "training_metadata.json");
  await fs.copyFile(plyPath, localPlyPath);
  await fs.writeFile(localMetadataPath, `${JSON.stringify(metadata, null, 2)}\n`, "utf8");
  await execFileAsync("tar", ["-czf", tarPath, "training_metadata.json", "splat.ply"], { cwd: workDir });
}

