version: 0.2

env:
  variables:
    AWS_REGION: "us-west-2"
    AWS_ACCOUNT_ID: "975050048887"
    CONTAINERS_TO_BUILD: "all"
    # Docker layer caching optimization
    DOCKER_BUILDKIT: "1"
    BUILDKIT_PROGRESS: "plain"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install awscli --upgrade
      - echo "Enabling Docker BuildKit for improved caching..."
      - export DOCKER_BUILDKIT=1

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - echo "Making deployment script executable..."
      - chmod +x scripts/deployment/deploy.sh
      - 'echo "Containers to build: $CONTAINERS_TO_BUILD"'
      - echo "Starting optimized build process with enhanced caching..."
      - echo "Build optimization: Docker layer caching enabled"

  build:
    commands:
      - echo "Starting container build process..."
      - 'echo "Building: $CONTAINERS_TO_BUILD"'
      - echo "Build started at: $(date)"
      - ./scripts/deployment/deploy.sh $CONTAINERS_TO_BUILD
      - echo "Build completed at: $(date)"

  post_build:
    commands:
      - echo "Build process completed on `date`"
      - echo "Cleaning up temporary files..."
      - docker system prune -f --filter "until=24h" || true

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip'
    - '/root/.docker/buildx'
    - '/root/.cache/docker'
    - '/var/lib/docker/overlay2' 