version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 975050048887.dkr.ecr.us-west-2.amazonaws.com
      - echo Build started on `date`
      - echo Building the Docker image...
  build:
    commands:
      - cd infrastructure/containers/compressor
      - docker build -f Dockerfile.production -t sogs-production:latest .
      - docker tag sogs-production:latest 975050048887.dkr.ecr.us-west-2.amazonaws.com/sogs-production:latest
      - docker tag sogs-production:latest 975050048887.dkr.ecr.us-west-2.amazonaws.com/sogs-production:production-$(date +%s)
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 975050048887.dkr.ecr.us-west-2.amazonaws.com/sogs-production:latest
      - docker push 975050048887.dkr.ecr.us-west-2.amazonaws.com/sogs-production:production-$(date +%s)
      - echo Push completed
artifacts:
  files:
    - '**/*'
