version: 0.2

env:
  variables:
    AWS_REGION: "us-west-2"
    AWS_ACCOUNT_ID: "975050048887" # This will be automatically replaced by CodeBuild's role

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install awscli --upgrade

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Logging in to AWS Public ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - echo "Making deployment script executable..."
      - chmod +x scripts/deployment/deploy.sh

  build:
    commands:
      - echo "Starting container build process..."
      - ./scripts/deployment/deploy.sh all

  post_build:
    commands:
      - echo "Build process completed on `date`"

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip'
    - '/root/.docker/buildx' 