'use client';
/* eslint-disable react/no-unescaped-entities */
import { useState } from 'react';

interface TermsOfServiceModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function TermsOfServiceModal({ isOpen, onClose }: TermsOfServiceModalProps): JSX.Element {
  if (!isOpen) return <></>;

  return (
    <div className="terms-modal-overlay" onClick={onClose}>
      <div className="terms-modal" onClick={(e) => e.stopPropagation()}>
        <div className="terms-modal-content">
          <div className="terms-modal-close-container">
            <button className="terms-modal-close" onClick={onClose}>
              <img src="/assets/SpaceportIcons/Close.svg" alt="Close" />
            </button>
          </div>
          
          <h1>Service Agreement</h1>
          <p className="terms-company-info">SPACEPORT AI LLC, a Utah limited liability company ("Company")</p>
          <p className="terms-intro">This Service Agreement ("Agreement") governs your ("Client") use of the Company's services. By uploading content or using our platform, you agree to the following terms:</p>
          
          <h2>1. Services Provided</h2>
          <p>The Company provides automated drone pathing and 3D modeling services. Clients capture drone imagery, which the Company processes into 3D models for property marketing and related applications.</p>

          <h2>2. Client Responsibilities</h2>
          <ul>
            <li>The Client is solely responsible for the safe and lawful operation of drones.</li>
            <li>The Client must review and approve all flight paths before operation.</li>
            <li>The Client is solely responsible for compliance with all aviation, privacy, and property laws in their jurisdiction.</li>
          </ul>

          <h2>3. Ownership & Licensing</h2>
          <p><strong>Footage:</strong> The Client retains ownership of drone footage they capture. By uploading footage, the Client grants the Company an irrevocable, perpetual, worldwide, royalty-free license to use, reproduce, modify, distribute, display, and create derivative works from the footage for any purpose, including but not limited to model generation, marketing, advertising, research, and commercial applications. If the Client wishes to restrict the Company's rights of use (e.g., a "private tier"), this must be expressly agreed to in a separate written agreement signed by the Company. Unless such a written agreement exists, the Company retains full rights as stated above.</p>
          <p><strong>3D Models:</strong> All 3D models generated by the Company remain the exclusive property of the Company. By using the service, the Client grants the Company an irrevocable, perpetual, worldwide, royalty-free license to use, reproduce, modify, distribute, display, and create derivative works from the models for any purpose, including but not limited to marketing, advertising, research, and commercial applications. The Client is granted a limited, non-exclusive, revocable, commercial license to use the models only while subscribed and only within the limits of their subscription tier. Models cannot be downloaded, resold, sublicensed, or used after cancellation of subscription.</p>

          <h2>4. Subscriptions & Payments</h2>
          <ul>
            <li>Access to services and models is subscription-based.</li>
            <li>Subscription tiers, prices, and features are subject to change at any time. The Company will make reasonable efforts to provide notice prior to the start of the next billing period in which the changes take effect. However, failure to provide notice shall not create liability for the Company.</li>
            <li>Payment of the subscription fee grants the Client access to the number of models available within their tier for the billing period that follows payment.</li>
            <li>Failure to maintain an active subscription immediately revokes the Client's license to access and use models.</li>
            <li>Cancellation does not entitle the Client to refunds for unused portions of a billing cycle.</li>
          </ul>

          <h2>5. Limitation of Liability</h2>
          <p>To the fullest extent permitted by law, the Company shall not be liable for any damages arising from the use of its services. This includes, without limitation, damage to drones, property, aircraft, persons, data, or reputations.</p>

          <h2>6. Indemnification</h2>
          <p>The Client agrees to fully indemnify, defend, and hold harmless the Company, its officers, employees, and contractors from any claims, damages, fines, penalties, or expenses arising out of:</p>
          <ul>
            <li>Drone operation by the Client.</li>
            <li>Content or footage uploaded by the Client.</li>
            <li>Violations of law, privacy, or property rights.</li>
          </ul>

          <h2>7. Data & Confidentiality Disclaimer</h2>
          <p>The Client acknowledges and agrees that the Company is not a custodian of the Client's confidential data and provides no confidentiality guarantees. The Client is solely responsible for ensuring that uploaded content complies with all applicable privacy, property, and confidentiality obligations.</p>

          <h2>8. Termination</h2>
          <ul>
            <li>The Client may cancel their subscription at any time through their account.</li>
            <li>Upon cancellation or non-payment, all rights and licenses to use models are immediately revoked.</li>
            <li>The Company may, at its sole discretion, retain and use models and footage for archival, research, marketing, advertising, or other commercial purposes, unless a separate written agreement signed by the Company provides otherwise.</li>
          </ul>

          <h2>9. Governing Law & Jurisdiction</h2>
          <p>This Agreement is governed by the laws of the State of Utah, without regard to conflict-of-law principles. Any disputes shall be brought in a court chosen at the sole discretion of the Company, in any jurisdiction worldwide, and the parties consent to such jurisdiction and venue.</p>

          <h2>10. Entire Agreement</h2>
          <p>This Agreement represents the full understanding between the parties and supersedes all prior agreements. No modifications are valid unless in writing and signed by the Company.</p>

          <p className="terms-conclusion">By using Spaceport's services, you acknowledge and agree to these terms in full.</p>
        </div>
      </div>
    </div>
  );
}
