# ~/.codex/config.toml
approval_mode = "full_access"
model = "gpt-5-codex"
model_reasoning_effort = "high"

# (Optional) MCP servers, etc.
# [mcp_servers.playwright]
# command = "npx"
# args = ["@playwright/mcp@latest"]

[projects."/Users/gabrielhansen/v0-spaceport-website"]
trust_level = "trusted"

[projects."/Users/gabrielhansen/user-development-spaceport-website"]
trust_level = "trusted"