# OpenSfM Configuration for GPS-Constrained Drone Reconstruction
# Optimized for 3DGS compatibility with ~30,000 high-quality points
# Updated: 2025-01-27

# GPS and Coordinate System Configuration
use_altitude_tag: true
align_method: 'orientation_prior'
align_orientation_prior: 'vertical'

# GPS Prior Configuration - ENHANCED for accuracy
use_gps: true
gps_error_threshold: 5.0   # meters - tighter constraint for better accuracy
gps_accuracy: 3.0         # assumed GPS accuracy in meters - more precise

# Camera and Image Processing
camera_calibration_linear_constraint_weight: 100.0
camera_calibration_nonlinear_constraint_weight: 100.0

# Feature Detection - OPTIMIZED for quality over quantity
feature_type: 'sift'
feature_min_frames: 6000    # INCREASED: Stricter quality threshold
feature_process_size: 2048  # High resolution for drone imagery
feature_use_adaptive_suppression: false
feature_max_num_features: 8000  # REDUCED: Focus on quality features

sift_peak_threshold: 0.015   # INCREASED: Higher quality threshold for better features
sift_edge_threshold: 15      # INCREASED: Better edge filtering

# Feature Matching - OPTIMIZED for GPS-constrained reconstruction
matching_gps_distance: 150   # REDUCED: Tighter GPS constraints for better accuracy
matching_time_neighbors: 20  # REDUCED: More focused temporal matching
matcher_type: 'flann'
lowes_ratio: 0.7             # STRICTER: Better match filtering
matcher_distance: 0.6        # STRICTER: Tighter distance threshold

# Robust matching for challenging drone scenarios
robust_matching_calib_threshold: 4.0
robust_matching_threshold: 4.0
robust_matching_min_match: 15  # INCREASED: Higher quality matches

# Bundle Adjustment Configuration - ENHANCED for quality
optimize_camera_parameters: true
bundle_adjustment_max_num_iterations: 200  # INCREASED: Better convergence
bundle_adjustment_loss_function: 'SoftLOneLoss'
bundle_adjustment_loss_function_threshold: 0.8  # STRICTER: Better outlier rejection

# GPS-specific bundle adjustment settings
bundle_use_gps: true
bundle_use_gcp: false
bundle_max_num_shots: 500

# Reconstruction Settings - OPTIMIZED for 3DGS compatibility
reconstruct_with_gps: true
triangulation_threshold: 0.003      # STRICTER: Better point filtering
triangulation_min_ray_angle: 2.0    # INCREASED: Better triangulation angles (degrees)

# Resection settings - ENHANCED for accuracy
resection_threshold: 0.2            # STRICTER: Better camera registration
resection_min_inliers: 20           # INCREASED: Higher quality resection

# Track Creation - OPTIMIZED
tracker_type: 'incremental'
retriangulation: true
retriangulation_ratio: 1.1          # REDUCED: Less aggressive retriangulation

# GPS Coordinate Reference
# Will be set dynamically based on flight data
reference_lla: [0.0, 0.0, 0.0]  # Placeholder - set by GPS processor

# Dense Matching (minimal for 3DGS compatibility)
depthmap_resolution: 640
depthmap_min_depth: 0.01
depthmap_max_depth: 1000

# Process Configuration
processes: 4  # Match SageMaker instance vCPUs

# Output Settings
save_partial_reconstructions: true   # Enable for 3DGS train/test split
local_bundle_radius: 3

# Mesh Generation (disabled for 3DGS pipeline)
mesh_size: 0  # Disable mesh generation

# Quality Control - ENHANCED for 3DGS
min_reconstructed_points: 5000      # INCREASED: Ensure sufficient points
max_reconstructed_points: 50000     # NEW: Cap maximum points for 3DGS
remove_max_outliers: 30             # REDUCED: Less aggressive outlier removal

# Advanced GPS Integration Settings
gps_dop_threshold: 10.0        # Dilution of precision threshold
gps_min_satellites: 4          # Minimum GPS satellites
auto_compute_image_connectivity: true

# Camera Model Selection
default_camera_model: 'perspective'  # Most drones use perspective cameras
camera_models:
  perspective:
    focal_prior_weight: 1.0
    k1_prior_weight: 0.1  
    k2_prior_weight: 0.1

# Incremental Reconstruction Settings
incremental_bundle_size: 100
incremental_bundle_steps: 10

# Geometric Verification 
compute_two_view_geometry: true
two_view_geometry_threshold: 1e-8

# Metadata Processing
extract_metadata: true
use_exif_size: true
use_exif_focal: true

# 3DGS-specific settings
reconstruction_split_ratio: 0.8     # 80% training, 20% validation
reconstruction_split_method: 'sequential'  # Sequential split for temporal consistency

# Logging and Debug
log_level: 'INFO'
save_debug_files: false 