#!/usr/bin/env bash
# Setup local environment variables for development
# This script creates web/.env.local by prompting for the Google Maps API key

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB_DIR="$SCRIPT_DIR/../web"
ENV_LOCAL="$WEB_DIR/.env.local"

echo "================================================"
echo "Spaceport Local Environment Setup"
echo "================================================"
echo ""
echo "This script will create web/.env.local for local development."
echo ""

# Check if .env.local already exists
if [ -f "$ENV_LOCAL" ]; then
  echo "⚠️  $ENV_LOCAL already exists."
  read -p "Overwrite it? (y/N): " -n 1 -r
  echo ""
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted. Existing .env.local preserved."
    exit 0
  fi
fi

# Try to get the API key from GitHub secrets (requires gh CLI and permissions)
echo "Attempting to retrieve NEXT_PUBLIC_GOOGLE_MAPS_API_KEY from GitHub secrets..."
GOOGLE_MAPS_KEY=""

if command -v gh &> /dev/null; then
  # Note: gh secret get won't work for security reasons, but we try anyway
  if GOOGLE_MAPS_KEY=$(gh secret get NEXT_PUBLIC_GOOGLE_MAPS_API_KEY 2>/dev/null); then
    echo "✅ Retrieved key from GitHub secrets"
  else
    echo "⚠️  Cannot retrieve secret value directly (GitHub security)"
  fi
fi

# If we don't have the key, prompt for it
if [ -z "$GOOGLE_MAPS_KEY" ]; then
  echo ""
  echo "Please provide your Google Maps API key."
  echo "You can find it at: https://console.cloud.google.com/apis/credentials"
  echo "Or ask the repo maintainer for the value of NEXT_PUBLIC_GOOGLE_MAPS_API_KEY"
  echo ""
  read -p "Enter Google Maps API Key: " GOOGLE_MAPS_KEY
  
  if [ -z "$GOOGLE_MAPS_KEY" ]; then
    echo "❌ API key cannot be empty"
    exit 1
  fi
fi

# Optionally get the Map ID
echo ""
echo "Please provide your Google Maps Map ID (optional, press Enter to skip)."
read -p "Enter Google Maps Map ID: " GOOGLE_MAPS_MAP_ID

# Create .env.local
echo "Creating $ENV_LOCAL..."
cat > "$ENV_LOCAL" << EOF
# Local Development Environment Variables
# Auto-generated by scripts/setup-local-env.sh
# DO NOT COMMIT THIS FILE (already in .gitignore)

# Google Maps Configuration
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_KEY
NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID=${GOOGLE_MAPS_MAP_ID:-}

# Add other NEXT_PUBLIC_* vars as needed below:
# NEXT_PUBLIC_PROJECTS_API_URL=http://localhost:3001
# NEXT_PUBLIC_DRONE_PATH_API_URL=http://localhost:3002
# etc.
EOF

echo ""
echo "✅ Created $ENV_LOCAL"
echo ""
echo "Your local dev server will now have access to:"
echo "  - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY"
if [ -n "${GOOGLE_MAPS_MAP_ID:-}" ]; then
  echo "  - NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID"
fi
echo ""
echo "Run 'npm run dev' in the web/ directory to test."
echo "================================================"

