#!/usr/bin/env bash
# Auto-setup local environment variables from AWS CDK/CloudFormation
# This script automatically fetches API URLs and Cognito config from deployed stacks

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB_DIR="$SCRIPT_DIR/../web"
ENV_LOCAL="$WEB_DIR/.env.local"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

print_status() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

echo "================================================"
echo "🚀 Spaceport Auto Local Environment Setup"
echo "================================================"
echo ""
echo "This script will automatically fetch environment variables from AWS"
echo "and create web/.env.local for local development."
echo ""

# Check prerequisites
if ! command -v aws &> /dev/null; then
    print_error "AWS CLI not found. Please install it first."
    exit 1
fi

if ! command -v jq &> /dev/null; then
    print_error "jq not found. Please install it: brew install jq"
    exit 1
fi

# Check if .env.local already exists
if [ -f "$ENV_LOCAL" ]; then
    echo "⚠️  $ENV_LOCAL already exists."
    read -p "Overwrite it? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted. Existing .env.local preserved."
        exit 0
    fi
fi

# Determine which environment to use (staging/preview by default)
ENVIRONMENT="${1:-staging}"
if [ "$ENVIRONMENT" = "production" ] || [ "$ENVIRONMENT" = "prod" ]; then
    ENV_SUFFIX="Production"
    STACK_SUFFIX="Stack"
else
    ENV_SUFFIX="Staging"
    STACK_SUFFIX="StagingStack"
fi

print_status "Using $ENVIRONMENT environment (stacks: *${STACK_SUFFIX})"
echo ""

# Start building .env.local
ENV_CONTENT="# Local Development Environment Variables
# Auto-generated by scripts/setup-local-env-auto.sh
# DO NOT COMMIT THIS FILE (already in .gitignore)
# Generated: $(date)

"

# 1. Fetch Cognito Configuration
print_status "Fetching Cognito configuration..."
COGNITO_STACK="SpaceportAuth${ENV_SUFFIX}Stack"
COGNITO_OUTPUTS=$(aws cloudformation describe-stacks \
    --stack-name "$COGNITO_STACK" \
    --query "Stacks[0].Outputs[?contains(OutputKey, 'Cognito')].{Key:OutputKey,Value:OutputValue}" \
    --output json 2>/dev/null || echo "[]")

if [ "$COGNITO_OUTPUTS" != "[]" ] && [ -n "$COGNITO_OUTPUTS" ]; then
    USER_POOL_ID=$(echo "$COGNITO_OUTPUTS" | jq -r '.[] | select(.Key=="CognitoUserPoolId") | .Value // empty')
    CLIENT_ID=$(echo "$COGNITO_OUTPUTS" | jq -r '.[] | select(.Key=="CognitoUserPoolClientId") | .Value // empty')
    
    if [ -n "$USER_POOL_ID" ] && [ -n "$CLIENT_ID" ]; then
        ENV_CONTENT+="# Cognito Configuration (from $COGNITO_STACK)
NEXT_PUBLIC_COGNITO_REGION=us-west-2
NEXT_PUBLIC_COGNITO_USER_POOL_ID=$USER_POOL_ID
NEXT_PUBLIC_COGNITO_USER_POOL_CLIENT_ID=$CLIENT_ID

"
        print_success "✅ Cognito config fetched"
    else
        print_warning "⚠️  Cognito config incomplete, skipping"
    fi
else
    print_warning "⚠️  $COGNITO_STACK not found or no Cognito outputs"
fi

# 2. Fetch API URLs from SpaceportStack
print_status "Fetching API URLs from Spaceport${ENV_SUFFIX}Stack..."
MAIN_STACK="Spaceport${STACK_SUFFIX}"
API_OUTPUTS=$(aws cloudformation describe-stacks \
    --stack-name "$MAIN_STACK" \
    --query "Stacks[0].Outputs[?contains(OutputKey, 'ApiUrl')].{Key:OutputKey,Value:OutputValue}" \
    --output json 2>/dev/null || echo "[]")

if [ "$API_OUTPUTS" != "[]" ] && [ -n "$API_OUTPUTS" ]; then
    ENV_CONTENT+="# API Endpoints (from $MAIN_STACK)
"
    
    echo "$API_OUTPUTS" | jq -r '.[] | "\(.Key),\(.Value)"' | while IFS=',' read -r key value; do
        case "$key" in
            *DronePathApiUrl*)
                ENV_CONTENT+="NEXT_PUBLIC_DRONE_PATH_API_URL=$value
"
                print_success "  ✅ Drone Path API"
                ;;
            *FileUploadApiUrl*)
                ENV_CONTENT+="NEXT_PUBLIC_FILE_UPLOAD_API_URL=$value
"
                print_success "  ✅ File Upload API"
                ;;
            *WaitlistApiUrl*)
                ENV_CONTENT+="NEXT_PUBLIC_WAITLIST_API_URL=$value
"
                print_success "  ✅ Waitlist API"
                ;;
            *FeedbackApiUrl*)
                ENV_CONTENT+="NEXT_PUBLIC_FEEDBACK_API_URL=$value
"
                print_success "  ✅ Feedback API"
                ;;
        esac
    done
    ENV_CONTENT+="
"
else
    print_warning "⚠️  $MAIN_STACK not found or no API URLs"
fi

# 3. Fetch API URLs from AuthStack
print_status "Fetching API URLs from SpaceportAuth${ENV_SUFFIX}Stack..."
AUTH_STACK="SpaceportAuth${STACK_SUFFIX}"
AUTH_OUTPUTS=$(aws cloudformation describe-stacks \
    --stack-name "$AUTH_STACK" \
    --query "Stacks[0].Outputs[?contains(OutputKey, 'ApiUrl')].{Key:OutputKey,Value:OutputValue}" \
    --output json 2>/dev/null || echo "[]")

if [ "$AUTH_OUTPUTS" != "[]" ] && [ -n "$AUTH_OUTPUTS" ]; then
    echo "$AUTH_OUTPUTS" | jq -r '.[] | "\(.Key),\(.Value)"' | while IFS=',' read -r key value; do
        case "$key" in
            *ProjectsApiUrl*)
                ENV_CONTENT+="NEXT_PUBLIC_PROJECTS_API_URL=$value
"
                print_success "  ✅ Projects API"
                ;;
            *BetaAccessAdminApiUrl*)
                ENV_CONTENT+="NEXT_PUBLIC_BETA_ACCESS_API_URL=$value
"
                print_success "  ✅ Beta Access API"
                ;;
            *LitchiApiUrl*)
                ENV_CONTENT+="NEXT_PUBLIC_LITCHI_API_URL=$value
"
                print_success "  ✅ Litchi API"
                ;;
        esac
    done
    ENV_CONTENT+="
"
fi

# 4. Fetch ML Pipeline API URL
print_status "Fetching ML Pipeline API URL..."
ML_STACK="SpaceportMLPipeline${STACK_SUFFIX}"
ML_API_URL=$(aws cloudformation describe-stacks \
    --stack-name "$ML_STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='MLPipelineApiUrl'].OutputValue" \
    --output text 2>/dev/null || echo "")

if [ -n "$ML_API_URL" ] && [ "$ML_API_URL" != "None" ]; then
    ENV_CONTENT+="NEXT_PUBLIC_ML_PIPELINE_API_URL=$ML_API_URL
"
    print_success "  ✅ ML Pipeline API"
    ENV_CONTENT+="
"
fi

# 5. Fetch Subscription API URL (if available)
print_status "Checking for Subscription API..."
SUBSCRIPTION_API_URL=$(aws cloudformation describe-stacks \
    --stack-name "$AUTH_STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='SubscriptionApiUrl'].OutputValue" \
    --output text 2>/dev/null || echo "")

if [ -n "$SUBSCRIPTION_API_URL" ] && [ "$SUBSCRIPTION_API_URL" != "None" ]; then
    ENV_CONTENT+="NEXT_PUBLIC_SUBSCRIPTION_API_URL=$SUBSCRIPTION_API_URL
"
    print_success "  ✅ Subscription API"
    ENV_CONTENT+="
"
fi

# 6. Prompt for Google Maps API Key (can't be auto-fetched)
ENV_CONTENT+="# Google Maps Configuration (REQUIRED for flight viewer)
# Get your key from: https://console.cloud.google.com/apis/credentials
"
print_status "Google Maps API Key is required for flight viewer..."
read -p "Enter Google Maps API Key (or press Enter to skip): " GOOGLE_MAPS_KEY
if [ -n "$GOOGLE_MAPS_KEY" ]; then
    ENV_CONTENT+="NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_KEY
"
    read -p "Enter Google Maps Map ID (optional, press Enter to skip): " GOOGLE_MAPS_MAP_ID
    if [ -n "$GOOGLE_MAPS_MAP_ID" ]; then
        ENV_CONTENT+="NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID=$GOOGLE_MAPS_MAP_ID
"
    fi
    ENV_CONTENT+="
"
else
    ENV_CONTENT+="# NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=your-key-here
# NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID=your-map-id-here
"
fi

# 7. Add optional Stripe key (for subscription testing)
ENV_CONTENT+="# Stripe Configuration (optional, for subscription testing)
# Use test keys for local development: pk_test_...
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_...

"

# Write the file
echo "$ENV_CONTENT" > "$ENV_LOCAL"

echo ""
echo "================================================"
print_success "✅ Created $ENV_LOCAL"
echo ""
echo "📋 Summary of configured variables:"
grep -E "^NEXT_PUBLIC_" "$ENV_LOCAL" | sed 's/=.*/=***/' | sed 's/^/  ✅ /'
echo ""
echo "🚀 Next steps:"
echo "  1. Restart your dev server: npm run dev"
echo "  2. Sign in should now work!"
echo ""
echo "💡 Tip: Run this script again anytime to refresh API URLs"
echo "================================================"
