name: Deploy Next.js to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches: [ main, development ]
    paths:
      - 'web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - name: Select target Pages project per branch
        id: select_project
        run: |
          BRANCH="${{ github.ref_name }}"
          if [ "$BRANCH" = "main" ]; then
            TARGET="v0-spaceport-website-prod-fresh"
          else
            TARGET="v0-spaceport-website-preview2"
          fi
          echo "CF_PAGES_PROJECT=$TARGET" >> $GITHUB_ENV
          echo "project=$TARGET" >> $GITHUB_OUTPUT
          echo "Using CF Pages project: $TARGET for branch $BRANCH"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install deps
        run: npm ci || npm install

      - name: Build Next for Cloudflare (SSR)
        run: |
          npm run build
          npx @cloudflare/next-on-pages
          # Workaround: ensure Worker picked up by Pages by placing _worker.js at build root
          if [ -f .vercel/output/static/_worker.js/index.js ]; then
            cp .vercel/output/static/_worker.js/index.js .vercel/output/_worker.js
          fi

      - name: Debug .vercel/output contents
        run: |
          echo "Listing .vercel/output" && ls -la .vercel/output || true
          echo "Functions manifest.json:" && (cat .vercel/output/functions/manifest.json || true)
          echo "Static dir:" && ls -la .vercel/output/static || true

      - name: Install Wrangler
        run: npm i -g wrangler@4

      - name: Ensure Pages runtime flags (compat date + node compat)
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          curl -fsS -X PATCH \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json" \
             "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${CF_PAGES_PROJECT}" \
            --data '{
              "deployment_configs": {
                "production": {
                  "compatibility_date": "2025-08-09",
                  "compatibility_flags": ["nodejs_compat", "nodejs_compat_populate_process_env"],
                  "build_image_major_version": 3
                },
                "preview": {
                  "compatibility_date": "2025-08-09",
                  "compatibility_flags": ["nodejs_compat", "nodejs_compat_populate_process_env"],
                  "build_image_major_version": 3
                }
              }
            }' | cat

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          BRANCH="${{ github.ref_name }}"
          npx wrangler pages deploy .vercel/output \
            --project-name "$CF_PAGES_PROJECT" \
            --branch "$BRANCH"

      - name: Resolve latest deployment URLs (preview alias + hash URL)
        id: resolve_urls
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          set -euo pipefail
          BRANCH="${{ github.ref_name }}"
          # Get most recent deployment for the selected project (includes preview)
          JSON=$(curl -fsSL -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${CF_PAGES_PROJECT}/deployments?per_page=1")
          HASH_URL=$(echo "$JSON" | jq -r '.result[0].url')
          DEPLOY_ID=$(echo "$JSON" | jq -r '.result[0].id')
          # Fetch aliases for that deployment (branch alias if any)
          DETAIL=$(curl -fsSL -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${CF_PAGES_PROJECT}/deployments/${DEPLOY_ID}")
          ALIAS=$(echo "$DETAIL" | jq -r '.result.aliases[0] // empty')
          echo "hash_url=$HASH_URL" >> $GITHUB_OUTPUT
          echo "alias_url=$ALIAS" >> $GITHUB_OUTPUT
          echo "Resolved: HASH=$HASH_URL ALIAS=${ALIAS:-<none>}"

      - name: Verify preview alias and hash URL with retries
        env:
          HASH_URL: ${{ steps.resolve_urls.outputs.hash_url }}
          ALIAS_URL: ${{ steps.resolve_urls.outputs.alias_url }}
        run: |
          set -e
          urls=""
          if [ -n "$ALIAS_URL" ]; then urls="$urls $ALIAS_URL"; fi
          if [ -n "$HASH_URL" ]; then urls="$urls $HASH_URL"; fi
          echo "Checking URLs: $urls"
          for URL in $urls; do
            echo "Probing $URL ..."
            for i in $(seq 1 12); do
              echo "Attempt $i"
              if curl -fsS "$URL/health.txt" >/dev/null; then echo "OK $URL/health.txt"; break; fi
              sleep 5
              if [ $i -eq 12 ]; then echo "Timeout waiting for $URL"; exit 1; fi
            done
          done
