name: Deploy Next.js to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches: [ main, development ]
    paths:
      - 'web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: web
    env:
      CF_PAGES_PROJECT: v0-spaceport-website
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install deps
        run: npm ci || npm install

      - name: Build Next for Cloudflare (SSR)
        run: |
          npm run build
          npx @cloudflare/next-on-pages

      - name: Debug .vercel/output contents
        run: |
          echo "Listing .vercel/output" && ls -la .vercel/output || true
          echo "Functions manifest.json:" && (cat .vercel/output/functions/manifest.json || true)
          echo "Static dir:" && ls -la .vercel/output/static || true

      - name: Install Wrangler
        run: npm i -g wrangler@4

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          BRANCH="${{ github.ref_name }}"
          npx wrangler pages deploy .vercel/output \
            --project-name "$CF_PAGES_PROJECT" \
            --branch "$BRANCH"

      - name: Verify endpoints
        run: |
          HOST="https://$CF_PAGES_PROJECT.pages.dev"
          echo "Verifying $HOST"
          for path in "/" "/landing" "/about" "/pricing" "/create" "/signup" "/api/health" "/health.txt"; do
            echo "GET $HOST$path";
            curl -fsS "$HOST$path" -H 'Accept: text/html,application/json' >/dev/null || (echo "Failed: $path" && curl -i "$HOST$path" && exit 1);
          done
