name: Deploy Next.js to GitHub Pages (development)

on:
  push:
    branches: [ development ]
    paths:
      - 'web/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install deps
        run: npm ci || npm install

      - name: Build for static export
        env:
          NEXT_PUBLIC_BASE_PATH: '/v0-spaceport-website'
          NEXT_OUTPUT_EXPORT: '1'
        run: |
          npm run build
          npx next export

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/out
          force_orphan: true

name: Deploy Next.js to GitHub Pages (development)

on:
  push:
    branches: [ development ]
    paths:
      - 'web/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install deps
        run: npm ci || npm install

      - name: Build with basePath for GitHub Pages
        env:
          NEXT_PUBLIC_BASE_PATH: '/v0-spaceport-website'
        run: npm run build

      - name: Export static (Next 14 app router)
        run: |
          npx next export || true
          mkdir -p out
          cp -R .next/static out/_next/static || true
          cp -R public/* out/ 2>/dev/null || true
          echo '/*    /index.html   200' > out/_redirects

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/out
