name: Deploy Next.js to Cloudflare Pages (main & development)

on:
  push:
    branches: [ main, development ]
    paths:
      - 'web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install deps
        run: npm ci || npm install

      - name: Build Next for Cloudflare (dynamic)
        run: |
          # next-on-pages will handle output for Pages Functions
          npm run build
          npm run cf:build

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages (per-branch)
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_PAGES_PROJECT: ${{ secrets.CF_PAGES_PROJECT }}
        run: |
          BRANCH="${{ github.ref_name }}"
          wrangler pages deploy .vercel/output \
            --project-name "$CF_PAGES_PROJECT" \
            --branch "$BRANCH"

name: Deploy Next.js to Cloudflare Pages (main)

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install deps
        run: npm ci || npm install

      - name: Build Next (Cloudflare)
        run: npm run build

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare Pages
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          NEXT_PUBLIC_BASE_PATH: ''
        run: |
          npx @cloudflare/next-on-pages
          wrangler pages deploy ./.vercel/output/static --project-name=${{ secrets.CF_PAGES_PROJECT }} --branch=main
